# Generated by Django 3.2.25 on 2024-12-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Explores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='img')),
                ('duration', models.IntegerField()),
                ('price', models.FloatField()),
                ('expiry', models.DateField(default=True)),
            ],
            options={
                'db_table': 'travel',
            },
        ),
    ]
