# Generated by Django 3.2.25 on 2024-12-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'vendorregistration',
            },
        ),
        migrations.AlterField(
            model_name='explores',
            name='expiry',
            field=models.DateField(),
        ),
    ]
