# Generated by Django 3.2.25 on 2024-12-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20241226_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'vendorlogin',
            },
        ),
        migrations.AlterField(
            model_name='venreg',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
