# Generated by Django 3.2.25 on 2024-12-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_uselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='explores',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
