# Generated by Django 5.1.6 on 2025-03-04 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
    ]
